#!/bin/bash

# FlightPath Vercel Deployment Setup
# This script helps you set up GitHub Secrets for automatic Vercel deployment

echo "=== FlightPath Vercel Auto-Deploy Setup ==="
echo ""
echo "You need to add these secrets to your GitHub repo:"
echo ""
echo "1. Go to: https://github.com/dotandeb/flightpath/settings/secrets/actions"
echo ""
echo "2. Add these Repository Secrets:"
echo ""
echo "   Name: VERCEL_TOKEN"
echo "   Value: [Your Vercel token from https://vercel.com/account/tokens]"
echo ""
echo "   Name: VERCEL_ORG_ID"  
echo "   Value: [Your Vercel Org ID - get it from vercel.json in your project settings]"
echo ""
echo "   Name: VERCEL_PROJECT_ID"
echo "   Value: [Your Vercel Project ID - get it from vercel.json after first import]"
echo ""
echo "   Name: AMADEUS_API_KEY"
echo "   Value: brQ8OmTJIFY7RmDCuWwRNQc6cJWw2c2e"
echo ""
echo "   Name: AMADEUS_API_SECRET"
echo "   Value: ABas2BuGP00d5chH"
echo ""
echo "   Name: NEXT_PUBLIC_APP_URL"
echo "   Value: https://flightpath.solutions"
echo ""
echo "=== OR use the one-command setup ==="
echo ""
echo "If you have 'gh' CLI installed, run:"
echo "  gh auth login"
echo "  ./setup-secrets.sh"
echo ""
